/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package watersupply;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Abdullahi Dere
 */
public class accoutns extends javax.swing.JFrame {
Codes co = new Codes();
String id = null;
String exp_no;
public void clear(){
acc_name.setText("");
institution.setText("");
Balance.setText("");
}
    
    public accoutns() {
        initComponents();
         this.setLocationRelativeTo(null);
        this.setTitle("expense Charge");
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ch = new javax.swing.JLabel();
        acc_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        serTex = new javax.swing.JTextField();
        ser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        update1 = new javax.swing.JButton();
        delet = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        Balance = new javax.swing.JTextField();
        institution = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(23, 127, 117));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ch.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        ch.setForeground(new java.awt.Color(255, 255, 255));
        ch.setText("Acc_name");
        jPanel1.add(ch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        acc_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acc_nameActionPerformed(evt);
            }
        });
        jPanel1.add(acc_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 200, 38));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Balance");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Institution");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, -1));

        serTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serTexActionPerformed(evt);
            }
        });
        jPanel1.add(serTex, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 165, 50));

        ser.setBackground(new java.awt.Color(204, 204, 204));
        ser.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ser.setForeground(new java.awt.Color(0, 51, 51));
        ser.setText("Search");
        ser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serActionPerformed(evt);
            }
        });
        jPanel1.add(ser, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 139, 53));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Accounts Management");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 370, 60));

        save.setBackground(new java.awt.Color(204, 204, 204));
        save.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        save.setForeground(new java.awt.Color(0, 51, 51));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 139, 51));

        update1.setBackground(new java.awt.Color(204, 204, 204));
        update1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        update1.setForeground(new java.awt.Color(0, 51, 51));
        update1.setText("Update");
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });
        jPanel1.add(update1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 139, 51));

        delet.setBackground(new java.awt.Color(204, 204, 204));
        delet.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        delet.setForeground(new java.awt.Color(0, 51, 51));
        delet.setText("Delete");
        delet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletActionPerformed(evt);
            }
        });
        jPanel1.add(delet, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 139, 51));

        clear.setBackground(new java.awt.Color(204, 204, 204));
        clear.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        clear.setForeground(new java.awt.Color(0, 51, 51));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 139, 51));

        Balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceActionPerformed(evt);
            }
        });
        jPanel1.add(Balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 200, 38));

        institution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                institutionActionPerformed(evt);
            }
        });
        jPanel1.add(institution, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 200, 38));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acc_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acc_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acc_nameActionPerformed

    private void serTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serTexActionPerformed

    private void serActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serActionPerformed
        String sql = "SELECT * from accounts where acc_no ='"+serTex.getText()+"'";
        co.search(sql);
        //SimpleDateFormat sm = new SimpleDateFormat("yyyy-mm-dd");
        //date = sm.format(reg_date.getDate());
        try{

            if(co.rs.next()){
                id = co.rs.getString("acc_no");
                acc_name.setText(co.rs.getString("acc_name"));
                institution.setText(co.rs.getString("institution"));
                Balance.setText(co.rs.getString("balance"));
                serTex.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "record not found");
            }
        }catch(Exception exp){
            JOptionPane.showMessageDialog(null,exp.getMessage());
        }
    }//GEN-LAST:event_serActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
//        SimpleDateFormat sm = new SimpleDateFormat("yyyy-MM-dd");
//        date = sm.format(reg_date.getDate());
        if(acc_name.getText().equals("") || institution.getText().equals("") || Balance.getText().equals("") ){
           JOptionPane.showMessageDialog(null, "Please Fill all the blanks");
     }
        else{
             String oper = "insert";
            String sql = "call acc_pro('"+ acc_name.getText()+"','"+institution.getText()+"','"+Balance.getText()+"','"+oper+"',null)";
            co.setSQL(sql);
            clear();
        }
    }//GEN-LAST:event_saveActionPerformed

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
        if(id == null){
           JOptionPane.showMessageDialog(null, "Please Search Valid Id");
        }else{
        String oper = "update";
        String sql = "call acc_pro('"+ acc_name.getText()+"','"+institution.getText()+"','"+Balance.getText()+"','"+oper+"','"+id+"')";
        co.setSQL(sql);
        clear();
        }
    }//GEN-LAST:event_update1ActionPerformed

    private void deletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletActionPerformed

        if(id == null){
           JOptionPane.showMessageDialog(null, "Please Search Valid Id");
        }else{
        String oper = "delete";
        String sql = "call acc_pro('"+ acc_name.getText()+"','"+institution.getText()+"','"+Balance.getText()+"','"+oper+"','"+id+"')";
        co.setSQL(sql);
        clear();
        }
    }//GEN-LAST:event_deletActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // update
    }//GEN-LAST:event_clearActionPerformed

    private void BalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BalanceActionPerformed

    private void institutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_institutionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_institutionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accoutns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accoutns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accoutns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accoutns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accoutns().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Balance;
    private javax.swing.JTextField acc_name;
    private javax.swing.JLabel ch;
    private javax.swing.JButton clear;
    private javax.swing.JButton delet;
    private javax.swing.JTextField institution;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton save;
    private javax.swing.JButton ser;
    private javax.swing.JTextField serTex;
    private javax.swing.JButton update1;
    // End of variables declaration//GEN-END:variables
}
