/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package watersupply;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Abdullahi Dere
 */
public class address extends javax.swing.JFrame {

    Codes co = new Codes();

    public void display() {
        co.viewTable(Table, "select*from address ORDER by add_no ASC ");
    }// display 
    String id = null;

    public void clear() {
        dist.setText("");
        villa.setText("");
        zone.setText("");
    }

    public address() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Adress Registration");
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        display();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dist = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        villa = new javax.swing.JTextField();
        zon = new javax.swing.JLabel();
        zone = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        update = new javax.swing.JButton();
        Del = new javax.swing.JButton();
        clea = new javax.swing.JButton();
        ser = new javax.swing.JButton();
        serTex = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(23, 127, 117));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Register New Address");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 55, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Distric");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 149, -1, -1));

        dist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distActionPerformed(evt);
            }
        });
        jPanel1.add(dist, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 163, 233, 32));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Village");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 149, -1, -1));

        villa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                villaActionPerformed(evt);
            }
        });
        jPanel1.add(villa, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 172, 233, 32));

        zon.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        zon.setForeground(new java.awt.Color(255, 255, 255));
        zon.setText("Zone");
        jPanel1.add(zon, new org.netbeans.lib.awtextra.AbsoluteConstraints(937, 149, -1, -1));

        zone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoneActionPerformed(evt);
            }
        });
        jPanel1.add(zone, new org.netbeans.lib.awtextra.AbsoluteConstraints(1051, 164, 233, 32));

        save.setBackground(new java.awt.Color(204, 204, 204));
        save.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        save.setForeground(new java.awt.Color(0, 51, 51));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 263, 139, 51));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 1284, 310));

        update.setBackground(new java.awt.Color(204, 204, 204));
        update.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        update.setForeground(new java.awt.Color(0, 51, 51));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 263, 139, 51));

        Del.setBackground(new java.awt.Color(204, 204, 204));
        Del.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Del.setForeground(new java.awt.Color(0, 51, 51));
        Del.setText("Delete");
        Del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelActionPerformed(evt);
            }
        });
        jPanel1.add(Del, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 263, 139, 51));

        clea.setBackground(new java.awt.Color(204, 204, 204));
        clea.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        clea.setForeground(new java.awt.Color(0, 51, 51));
        clea.setText("Clear");
        clea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleaActionPerformed(evt);
            }
        });
        jPanel1.add(clea, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 263, 139, 51));

        ser.setBackground(new java.awt.Color(204, 204, 204));
        ser.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ser.setForeground(new java.awt.Color(0, 51, 51));
        ser.setText("Search");
        ser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serActionPerformed(evt);
            }
        });
        jPanel1.add(ser, new org.netbeans.lib.awtextra.AbsoluteConstraints(937, 39, 139, 53));

        serTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serTexActionPerformed(evt);
            }
        });
        jPanel1.add(serTex, new org.netbeans.lib.awtextra.AbsoluteConstraints(1094, 43, 165, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void distActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distActionPerformed

    private void villaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_villaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_villaActionPerformed

    private void zoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zoneActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed

        if (dist.getText().equals("") || villa.getText().equals("") || zone.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Fill all the blanks");
        } else {
            String oper = "insert";
            String sql = "call add_pro('" + dist.getText() + "','" + villa.getText() + "','" + zone.getText() + "','" + oper + "',null)";
            co.setSQL(sql);
            clear();
            display();
            dist.requestFocus();
        }
    }//GEN-LAST:event_saveActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
      if(id== null){
            JOptionPane.showMessageDialog(null, "Please Search Valid Id, Then delete");
        }else{
        String oper = "update";
        String sql = "call add_pro('" + dist.getText() + "','" + villa.getText() + "','" + zone.getText() + "','" + oper + "','" + id + "')";
        co.setSQL(sql);
        display();
        clear();
      }
    }//GEN-LAST:event_updateActionPerformed

    private void DelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelActionPerformed
        if(id== null){
            JOptionPane.showMessageDialog(null, "Please Search Valid Id, Then delete");
        }else{
        if (JOptionPane.showConfirmDialog(null, "Mahubtaa!") == JOptionPane.YES_OPTION) {
            //String sql = "delete from address where add_no ='"+ id+ "'";
            String oper = "delete";
            String sql = "call add_pro('" + dist.getText() + "','" + villa.getText() + "','" + zone.getText() + "','" + oper + "','" + id + "')";
            co.setSQL(sql);
            display();
            clear();
        }
        }
    }//GEN-LAST:event_DelActionPerformed

    private void cleaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleaActionPerformed
        clear();
    }//GEN-LAST:event_cleaActionPerformed

    private void serActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serActionPerformed
        String sql = "select * from address where add_no ='" + serTex.getText() + "'";
        co.search(sql);
        try {

            if (co.rs.next()) {
                id = co.rs.getString("add_no");
                dist.setText(co.rs.getString("district"));
                villa.setText(co.rs.getString("village"));
                zone.setText(co.rs.getString("zone"));
                serTex.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "record not found");
            }
        } catch (Exception exp) {
            JOptionPane.showMessageDialog(null, exp.getMessage());
        }
    }//GEN-LAST:event_serActionPerformed

    private void serTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serTexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(address.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(address.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(address.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(address.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new address().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Del;
    private javax.swing.JTable Table;
    private javax.swing.JButton clea;
    private javax.swing.JTextField dist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton save;
    private javax.swing.JButton ser;
    private javax.swing.JTextField serTex;
    private javax.swing.JButton update;
    private javax.swing.JTextField villa;
    private javax.swing.JLabel zon;
    private javax.swing.JTextField zone;
    // End of variables declaration//GEN-END:variables
}
