/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package watersupply;

import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Abdullahi Dere
 */
public class DashBoard extends javax.swing.JFrame {

    Codes co = new Codes();
    String singleReports = "";
    String singleBilsReport = "";
    String singExpesenRep = "";
    String date;
    String date1;
            
    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Water Managemet System");
        // Address
        String sql = "SELECT COUNT(add_no)As addcount FROM address";
        String colm = "addcount";
        co.count(TotVil, sql, colm);
        // single receipts report
         String singReport = "SELECT CONCAT(people_no, ',', name) AS person FROM people WHERE people_no IN (SELECT DISTINCT people_no FROM receipt) ORDER by people_no asc;";
         String col1 = "person";
         co.updateComo(singReports,singReport,col1);
        // Single Bils Report
         String singbilReport = "SELECT concat(people_no,',',name) as Bperson from bills b,customer_homes ch,people p where ch.cust_no = p.people_no and ch.cus_h_no = b.cus_H_no\n" +
                                  "GROUP by people_no";
         String per = "Bperson";
         co.updateComo(singleBills,singbilReport,per);
        // Expenses Report
        String SignEX = "SELECT concat(xc.ch_no,',',x.exp_name) as Expense FROM expense_peyment xp,expenses x,expense_charge xc where xc.ch_no = xp.ch_no and x.exp_no = xc.exp_no GROUP by xc.ch_no";
         String exs = "Expense";
         //co.updateComo(signExp,SignEX,exs);
        //  Total Customers
        String sql1 = "SELECT COUNT(people_no)As Peocount FROM people";
        String colm1 = "Peocount";
        co.count(TotCus, sql1, colm1);
         //  Total users
        String usesql = "SELECT COUNT(user_no)As useCount FROM users";
        String usecol = "useCount";
        co.count(touse, usesql, usecol);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        korsaar = new javax.swing.JPanel();
        topPanal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        userType = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        sidePanal = new javax.swing.JPanel();
        fan = new javax.swing.JButton();
        home = new javax.swing.JButton();
        serv = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        rep2 = new javax.swing.JButton();
        sepre = new javax.swing.JSeparator();
        usersBtn = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        main = new javax.swing.JTabbedPane();
        panal1 = new javax.swing.JPanel();
        poeple = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        touse = new javax.swing.JLabel();
        poeple1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        TotCus = new javax.swing.JLabel();
        poeple2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TotVil = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panal2 = new javax.swing.JPanel();
        panal5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cus = new javax.swing.JButton();
        add = new javax.swing.JButton();
        hom = new javax.swing.JButton();
        peo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        panal3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        rep = new javax.swing.JButton();
        bil = new javax.swing.JButton();
        expCh = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        panal4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rereport = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        rereport1 = new javax.swing.JButton();
        singleBills = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        unReceipReport = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        bilReport = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        sBilReport = new javax.swing.JButton();
        singReports = new javax.swing.JComboBox<>();
        expPay = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        Edate = new com.toedter.calendar.JDateChooser();
        Sdate = new com.toedter.calendar.JDateChooser();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        korsaar.setBackground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout korsaarLayout = new javax.swing.GroupLayout(korsaar);
        korsaar.setLayout(korsaarLayout);
        korsaarLayout.setHorizontalGroup(
            korsaarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1600, Short.MAX_VALUE)
        );
        korsaarLayout.setVerticalGroup(
            korsaarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(korsaar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1600, 30));

        topPanal.setBackground(new java.awt.Color(23, 127, 117));
        topPanal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Water Management System");
        topPanal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 679, 85));

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\Full stack Course\\water\\water-tap.png")); // NOI18N
        topPanal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 93, 85));

        userType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userType.setForeground(new java.awt.Color(255, 255, 255));
        topPanal.add(userType, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 120, 30));

        userName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setText(" ");
        topPanal.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 120, 30));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("User Name: ");
        topPanal.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("User type:");
        topPanal.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        getContentPane().add(topPanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1590, 120));

        sidePanal.setBackground(new java.awt.Color(23, 127, 117));
        sidePanal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fan.setBackground(new java.awt.Color(23, 127, 117));
        fan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fan.setForeground(new java.awt.Color(255, 255, 255));
        fan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finance.png"))); // NOI18N
        fan.setText("Finance");
        fan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        fan.setIconTextGap(6);
        fan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fanMouseExited(evt);
            }
        });
        fan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fanActionPerformed(evt);
            }
        });
        sidePanal.add(fan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 200, -1));

        home.setBackground(new java.awt.Color(23, 127, 117));
        home.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home (3).png"))); // NOI18N
        home.setText("Home");
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        home.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        home.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        home.setIconTextGap(6);
        home.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                homeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                homeFocusLost(evt);
            }
        });
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        sidePanal.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, -1));

        serv.setBackground(new java.awt.Color(23, 127, 117));
        serv.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        serv.setForeground(new java.awt.Color(255, 255, 255));
        serv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customer-service.png"))); // NOI18N
        serv.setText("Register");
        serv.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        serv.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        serv.setIconTextGap(6);
        serv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                servMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                servMouseExited(evt);
            }
        });
        serv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servActionPerformed(evt);
            }
        });
        sidePanal.add(serv, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 210, 70));

        logout.setBackground(new java.awt.Color(181, 39, 53));
        logout.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logout.setText("Logout");
        logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logout.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        logout.setIconTextGap(6);
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        sidePanal.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 200, 53));

        rep2.setBackground(new java.awt.Color(23, 127, 117));
        rep2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rep2.setForeground(new java.awt.Color(255, 255, 255));
        rep2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report (2).png"))); // NOI18N
        rep2.setText("Report");
        rep2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rep2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rep2.setIconTextGap(6);
        rep2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rep2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rep2MouseExited(evt);
            }
        });
        rep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rep2ActionPerformed(evt);
            }
        });
        sidePanal.add(rep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 200, 70));

        sepre.setForeground(new java.awt.Color(255, 255, 255));
        sepre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sidePanal.add(sepre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 210, 10));

        usersBtn.setBackground(new java.awt.Color(23, 127, 117));
        usersBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        usersBtn.setForeground(new java.awt.Color(255, 255, 255));
        usersBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/avatar-design.png"))); // NOI18N
        usersBtn.setText("Users");
        usersBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usersBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        usersBtn.setIconTextGap(6);
        usersBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usersBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usersBtnMouseExited(evt);
            }
        });
        usersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersBtnActionPerformed(evt);
            }
        });
        sidePanal.add(usersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 210, 60));

        jLabel40.setFont(new java.awt.Font("Arial Black", 0, 29)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Powered by ");
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel40MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel40MouseExited(evt);
            }
        });
        sidePanal.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 200, -1));

        getContentPane().add(sidePanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 210, 770));

        panal1.setBackground(new java.awt.Color(122, 186, 122));
        panal1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        poeple.setBackground(new java.awt.Color(23, 127, 117));
        poeple.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));
        poeple.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customer.png"))); // NOI18N
        poeple.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 80, 70));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total Users");
        poeple.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 190, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("permisions. Injoy Our Service");
        poeple.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 170, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Number of users which have");
        poeple.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 190, 20));

        touse.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        touse.setText("0");
        poeple.add(touse, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 40, 30));

        panal1.add(poeple, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 220, 210));

        poeple1.setBackground(new java.awt.Color(23, 127, 117));
        poeple1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));
        poeple1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customer.png"))); // NOI18N
        poeple1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 80, 70));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total Customers");
        poeple1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 190, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Number of Customers we are");
        poeple1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 190, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Saved. Injoy Our Service");
        poeple1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 170, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Number of Customers we are");
        poeple1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 190, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Saved. Injoy Our Service");
        poeple1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 170, 20));

        TotCus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TotCus.setText("0");
        poeple1.add(TotCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 40, 30));

        panal1.add(poeple1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 200, 210));

        poeple2.setBackground(new java.awt.Color(23, 127, 117));
        poeple2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));
        poeple2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/village.png"))); // NOI18N
        poeple2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 90, 80));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total Villages");
        poeple2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Avaible for you. Welcome");
        poeple2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 170, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Number of Village we are");
        poeple2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 170, -1));

        TotVil.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TotVil.setText("0");
        poeple2.add(TotVil, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 40, 30));

        panal1.add(poeple2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 200, 210));

        jLabel17.setFont(new java.awt.Font("Wide Latin", 0, 48)); // NOI18N
        jLabel17.setText("Market Analysis");
        panal1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel19.setFont(new java.awt.Font("Wide Latin", 0, 48)); // NOI18N
        jLabel19.setText("Our Service");
        panal1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anlays4.png"))); // NOI18N
        panal1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 470, 240));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bre3.png"))); // NOI18N
        jLabel24.setText("jLabel24");
        panal1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 290, 200));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bre2.png"))); // NOI18N
        jLabel25.setText("jLabel24");
        panal1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 300, 200));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bre4.png"))); // NOI18N
        jLabel26.setText("jLabel24");
        panal1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 380, 280, 200));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/freshWater.png"))); // NOI18N
        jLabel27.setText("jLabel24");
        panal1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 310, 200));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel28.setText("Bulk Water Tanker");
        panal1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 590, -1, -1));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel29.setText("Fresh Well Water");
        panal1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, -1, -1));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel30.setText("Fresh Borewell Water");
        panal1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 590, -1, -1));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel31.setText("Filter Drinking Water");
        panal1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 600, -1, -1));

        jPanel1.setBackground(new java.awt.Color(23, 127, 117));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panal1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, 1300, 30));

        jPanel2.setBackground(new java.awt.Color(23, 127, 117));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        panal1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 100, 780));

        main.addTab("tab1", panal1);

        panal2.setBackground(new java.awt.Color(122, 186, 122));
        panal2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panal5.setBackground(new java.awt.Color(23, 127, 117));
        panal5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 45)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("New Owner");
        panal5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 260, 75));

        cus.setBackground(new java.awt.Color(23, 127, 117));
        cus.setFont(new java.awt.Font("Times New Roman", 1, 33)); // NOI18N
        cus.setForeground(new java.awt.Color(255, 255, 255));
        cus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customer.png"))); // NOI18N
        cus.setText("custom_home");
        cus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cusMouseExited(evt);
            }
        });
        cus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusActionPerformed(evt);
            }
        });
        panal5.add(cus, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, -1, 74));

        add.setBackground(new java.awt.Color(23, 127, 117));
        add.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/placeholder.png"))); // NOI18N
        add.setText("Address");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        panal5.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 74));

        hom.setBackground(new java.awt.Color(23, 127, 117));
        hom.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        hom.setForeground(new java.awt.Color(255, 255, 255));
        hom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home (3).png"))); // NOI18N
        hom.setText("Homes");
        hom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homMouseExited(evt);
            }
        });
        hom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homActionPerformed(evt);
            }
        });
        panal5.add(hom, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 214, 74));

        peo.setBackground(new java.awt.Color(23, 127, 117));
        peo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        peo.setForeground(new java.awt.Color(255, 255, 255));
        peo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/youth.png"))); // NOI18N
        peo.setText("People");
        peo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                peoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                peoMouseExited(evt);
            }
        });
        peo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peoActionPerformed(evt);
            }
        });
        panal5.add(peo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 238, 74));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 45)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("New Customer");
        panal5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 300, 75));

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 45)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("New Tenant");
        panal5.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 290, 75));

        jLabel44.setBackground(new java.awt.Color(255, 255, 255));
        jLabel44.setFont(new java.awt.Font("Times New Roman", 1, 45)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("New Address");
        panal5.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 290, 75));

        panal2.add(panal5, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 49, 1120, 590));

        jPanel3.setBackground(new java.awt.Color(23, 127, 117));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        panal2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 0, 80, 780));

        jPanel4.setBackground(new java.awt.Color(23, 127, 117));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1470, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panal2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 770, 1470, 50));

        main.addTab("tab2", panal2);

        panal3.setBackground(new java.awt.Color(122, 186, 122));
        panal3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(23, 127, 117));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 45)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Accounts Managements");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 480, 75));

        rep.setBackground(new java.awt.Color(23, 127, 117));
        rep.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        rep.setForeground(new java.awt.Color(255, 255, 255));
        rep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/receipt.png"))); // NOI18N
        rep.setText("Receipts");
        rep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                repMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                repMouseExited(evt);
            }
        });
        rep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repActionPerformed(evt);
            }
        });
        jPanel7.add(rep, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 230, 70));

        bil.setBackground(new java.awt.Color(23, 127, 117));
        bil.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        bil.setForeground(new java.awt.Color(255, 255, 255));
        bil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bill.png"))); // NOI18N
        bil.setText("Bills");
        bil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bilMouseExited(evt);
            }
        });
        bil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilActionPerformed(evt);
            }
        });
        jPanel7.add(bil, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 200, 70));

        expCh.setBackground(new java.awt.Color(23, 127, 117));
        expCh.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        expCh.setForeground(new java.awt.Color(255, 255, 255));
        expCh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coins.png"))); // NOI18N
        expCh.setText("Accounts");
        expCh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                expChMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                expChMouseExited(evt);
            }
        });
        expCh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expChActionPerformed(evt);
            }
        });
        jPanel7.add(expCh, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 290, 70));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 45)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Do Receipts ");
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 300, 75));

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 45)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Charge Bills");
        jPanel7.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 270, 75));

        panal3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 1000, 710));

        jPanel5.setBackground(new java.awt.Color(23, 127, 117));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        panal3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 0, 80, 780));

        jPanel6.setBackground(new java.awt.Color(23, 127, 117));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1470, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panal3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 770, 1470, 50));

        main.addTab("tab3", panal3);

        panal4.setBackground(new java.awt.Color(122, 186, 122));
        panal4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(23, 127, 117));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Between Two date");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 330, 60));

        rereport.setBackground(new java.awt.Color(23, 127, 117));
        rereport.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        rereport.setForeground(new java.awt.Color(255, 255, 255));
        rereport.setText("Receipts Report");
        rereport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rereportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rereportMouseExited(evt);
            }
        });
        rereport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rereportActionPerformed(evt);
            }
        });
        jPanel8.add(rereport, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 210, 60));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Single Receipts Reports");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 390, 60));

        rereport1.setBackground(new java.awt.Color(23, 127, 117));
        rereport1.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        rereport1.setForeground(new java.awt.Color(255, 255, 255));
        rereport1.setText("Receipt by One");
        rereport1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rereport1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rereport1MouseExited(evt);
            }
        });
        rereport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rereport1ActionPerformed(evt);
            }
        });
        jPanel8.add(rereport1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 250, 210, 60));

        singleBills.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One " }));
        singleBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleBillsActionPerformed(evt);
            }
        });
        jPanel8.add(singleBills, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 350, 50));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("All UN_Receipts Reports");
        jPanel8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 400, 60));

        unReceipReport.setBackground(new java.awt.Color(23, 127, 117));
        unReceipReport.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        unReceipReport.setForeground(new java.awt.Color(255, 255, 255));
        unReceipReport.setText("Receipts Report");
        unReceipReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unReceipReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unReceipReportMouseExited(evt);
            }
        });
        unReceipReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unReceipReportActionPerformed(evt);
            }
        });
        jPanel8.add(unReceipReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 210, 60));

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("All Acounts Activities");
        jPanel8.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 330, 60));

        jButton1.setBackground(new java.awt.Color(23, 127, 117));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 420, 200, 60));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("All Bills Reports");
        jPanel8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 330, 60));

        bilReport.setBackground(new java.awt.Color(23, 127, 117));
        bilReport.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        bilReport.setForeground(new java.awt.Color(255, 255, 255));
        bilReport.setText("Show All Bills");
        bilReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bilReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bilReportMouseExited(evt);
            }
        });
        bilReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilReportActionPerformed(evt);
            }
        });
        jPanel8.add(bilReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 210, 60));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Single Bills Reports");
        jPanel8.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 330, 60));

        sBilReport.setBackground(new java.awt.Color(23, 127, 117));
        sBilReport.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        sBilReport.setForeground(new java.awt.Color(255, 255, 255));
        sBilReport.setText("Bills by One");
        sBilReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sBilReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sBilReportMouseExited(evt);
            }
        });
        sBilReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sBilReportActionPerformed(evt);
            }
        });
        jPanel8.add(sBilReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 210, 60));

        singReports.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One " }));
        singReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singReportsActionPerformed(evt);
            }
        });
        jPanel8.add(singReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 350, 50));

        expPay.setBackground(new java.awt.Color(23, 127, 117));
        expPay.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        expPay.setForeground(new java.awt.Color(255, 255, 255));
        expPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accounting.png"))); // NOI18N
        expPay.setText("Show accoutns");
        expPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                expPayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                expPayMouseExited(evt);
            }
        });
        expPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expPayActionPerformed(evt);
            }
        });
        jPanel8.add(expPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 590, 360, 70));

        jLabel41.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("All Receipts Reports");
        jPanel8.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 330, 60));
        jPanel8.add(Edate, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, 190, 30));
        jPanel8.add(Sdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 190, 30));

        panal4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1300, 750));

        jPanel9.setBackground(new java.awt.Color(23, 127, 117));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        panal4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 0, 80, 780));

        jPanel10.setBackground(new java.awt.Color(23, 127, 117));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1470, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panal4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 770, 1470, 50));

        main.addTab("tab4", panal4);

        getContentPane().add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 1390, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_homeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_homeFocusGained

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        main.setSelectedComponent(panal1);
    }//GEN-LAST:event_homeActionPerformed

    private void servActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servActionPerformed
        // TODO add your handling code here:
        main.setSelectedComponent(panal2);
    }//GEN-LAST:event_servActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_logoutActionPerformed

    private void fanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fanActionPerformed
        // TODO add your handling code here:
        main.setSelectedComponent(panal3);

    }//GEN-LAST:event_fanActionPerformed

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        // TODO add your handling code here:
        // home.setBackground(Color.red);
        home.setBackground(new Color(255, 153, 255));
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        // TODO add your handling code here:
        home.setBackground(new Color(23, 127, 117));

    }//GEN-LAST:event_homeMouseExited

    private void homeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_homeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_homeFocusLost

    private void servMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servMouseExited
        // TODO add your handling code here:
        serv.setBackground(new Color(23, 127, 117));
    }//GEN-LAST:event_servMouseExited

    private void servMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servMouseEntered
        // TODO add your handling code here:
        serv.setBackground(new Color(255, 153, 255));
    }//GEN-LAST:event_servMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        logout.setBackground(new Color(181, 39, 53));
    }//GEN-LAST:event_logoutMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        logout.setBackground(new Color(255, 0, 0));
    }//GEN-LAST:event_logoutMouseEntered

    private void fanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fanMouseExited
        // TODO add your handling code here:
        fan.setBackground(new Color(23, 127, 117));
    }//GEN-LAST:event_fanMouseExited

    private void fanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fanMouseEntered
        // TODO add your handling code here:
        fan.setBackground(new Color(255, 153, 255));
    }//GEN-LAST:event_fanMouseEntered

    private void peoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peoActionPerformed
        // TODO add your handling code here:
        peo_table peoTable = new peo_table();
        peoTable.show();
    }//GEN-LAST:event_peoActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        address add = new address();
        add.show();

    }//GEN-LAST:event_addActionPerformed

    private void homActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homActionPerformed
        homes home = new homes();
        home.show();

    }//GEN-LAST:event_homActionPerformed

    private void cusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusActionPerformed
        cus_h_Table cusH = new cus_h_Table();
        cusH.show();
    }//GEN-LAST:event_cusActionPerformed

    private void rep2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rep2MouseEntered
        // TODO add your handling code here:
        rep2.setBackground(new Color(255, 153, 255));
    }//GEN-LAST:event_rep2MouseEntered

    private void rep2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rep2MouseExited
        // TODO add your handling code here:
        rep2.setBackground(new Color(23, 127, 117));
    }//GEN-LAST:event_rep2MouseExited

    private void rep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rep2ActionPerformed
        // TODO add your handling code here:
        main.setSelectedComponent(panal4);
    }//GEN-LAST:event_rep2ActionPerformed

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        // TODO add your handling code here:
        add.setBackground(new Color(255, 153, 255));
    }//GEN-LAST:event_addMouseEntered

    private void peoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peoMouseEntered
        // TODO add your handling code here:
        peo.setBackground(new Color(255, 153, 255));
    }//GEN-LAST:event_peoMouseEntered

    private void homMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homMouseEntered
        // TODO add your handling code here:
        hom.setBackground(new Color(255, 153, 255));
    }//GEN-LAST:event_homMouseEntered

    private void cusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cusMouseEntered
        // TODO add your handling code here:
        cus.setBackground(new Color(255, 153, 255));
    }//GEN-LAST:event_cusMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        // TODO add your handling code here:
        add.setBackground(new Color(23, 127, 117));
    }//GEN-LAST:event_addMouseExited

    private void peoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peoMouseExited
        // TODO add your handling code here:
        peo.setBackground(new Color(23, 127, 117));
    }//GEN-LAST:event_peoMouseExited

    private void homMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homMouseExited
        // TODO add your handling code here:
        hom.setBackground(new Color(23, 127, 117));
    }//GEN-LAST:event_homMouseExited

    private void cusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cusMouseExited
        // TODO add your handling code here:
        cus.setBackground(new Color(23, 127, 117));
    }//GEN-LAST:event_cusMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Mahubtaa in aad ka baxayso", "Ma Hubtaa", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
//            System.exit(0);
            login log = new login();
            log.show();
            this.hide();
        }
    }//GEN-LAST:event_logoutMouseClicked

    private void repMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repMouseEntered
        // TODO add your handling code here:
        rep.setBackground(new Color(255, 153, 255));
    }//GEN-LAST:event_repMouseEntered

    private void repMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repMouseExited
        // TODO add your handling code here:
        rep.setBackground(new Color(23, 127, 117));
    }//GEN-LAST:event_repMouseExited

    private void repActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repActionPerformed
        // TODO add your handling code here:
        receipts rec = new receipts();
        rec.show();
    }//GEN-LAST:event_repActionPerformed

    private void bilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bilMouseEntered
        // TODO add your handling code here:
        bil.setBackground(new Color(255, 153, 255));
    }//GEN-LAST:event_bilMouseEntered

    private void bilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bilMouseExited
        // TODO add your handling code here:
        bil.setBackground(new Color(23, 127, 117));
    }//GEN-LAST:event_bilMouseExited

    private void bilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilActionPerformed
        bills bil = new bills();
        bil.show();
    }//GEN-LAST:event_bilActionPerformed

    private void expChMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expChMouseEntered
        // TODO add your handling code here:
        expCh.setBackground(new Color(255, 153, 255));
    }//GEN-LAST:event_expChMouseEntered

    private void expChMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expChMouseExited
        // TODO add your handling code here:
        expCh.setBackground(new Color(23, 127, 117));
    }//GEN-LAST:event_expChMouseExited

    private void expChActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expChActionPerformed
        // TODO add your handling code here:
        accoutns charg = new accoutns();
        charg.show();

    }//GEN-LAST:event_expChActionPerformed

    private void expPayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expPayMouseEntered
        // TODO add your handling code here:
        expPay.setBackground(new Color(255, 153, 255));
    }//GEN-LAST:event_expPayMouseEntered

    private void expPayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expPayMouseExited
        // TODO add your handling code here:
        expPay.setBackground(new Color(23, 127, 117));
    }//GEN-LAST:event_expPayMouseExited

    private void expPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expPayActionPerformed
    String accRpo = "call accReport_pro()";
    co.report("src\\watersupply\\accReport.jrxml", accRpo);  
            
        
    }//GEN-LAST:event_expPayActionPerformed

    private void rereportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rereportMouseExited
        // TODO add your handling code here:
        rereport.setBackground(new Color(23, 127, 117));
    }//GEN-LAST:event_rereportMouseExited

    private void rereportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rereportMouseEntered
        // TODO add your handling code here:
         rereport.setBackground(new Color(255, 153, 255));
    }//GEN-LAST:event_rereportMouseEntered

    private void rereport1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rereport1MouseEntered
        // TODO add your handling code here:
        rereport1.setBackground(new Color(255, 153, 255));
    }//GEN-LAST:event_rereport1MouseEntered

    private void rereport1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rereport1MouseExited
        // TODO add your handling code here:
        rereport1.setBackground(new Color(23, 127, 117));
    }//GEN-LAST:event_rereport1MouseExited

    private void rereportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rereportActionPerformed
       String sqlReport = "call allReceipts_pro()";
        co.report("src\\watersupply\\allReceiptsReports.jrxml", sqlReport);  
    }//GEN-LAST:event_rereportActionPerformed

    private void singleBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleBillsActionPerformed
        // TODO add your handling code here:
        String array[] = singleBills.getSelectedItem().toString().split(",");
        singleBilsReport = array[0];
    }//GEN-LAST:event_singleBillsActionPerformed

    private void rereport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rereport1ActionPerformed
        // TODO add your handling code here:
        String sqlReport = "call singleReceipts_pro('"+singleReports+"')";
        co.report("src\\watersupply\\receipts13.jrxml", sqlReport);
    }//GEN-LAST:event_rereport1ActionPerformed

    private void unReceipReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unReceipReportMouseEntered
        // TODO add your handling code here:
        unReceipReport.setBackground(new Color(255, 153, 255));
    }//GEN-LAST:event_unReceipReportMouseEntered

    private void unReceipReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unReceipReportMouseExited
        // TODO add your handling code here:
        unReceipReport.setBackground(new Color(23, 127, 117));
    }//GEN-LAST:event_unReceipReportMouseExited

    private void unReceipReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unReceipReportActionPerformed
        // TODO add your handling code here:
    String sqlReport = "call allUnReceipts_pro()";
    co.report("src\\watersupply\\unRecReport.jrxml", sqlReport);  
    
    }//GEN-LAST:event_unReceipReportActionPerformed

    private void bilReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bilReportMouseEntered
        // TODO add your handling code here:
        bilReport.setBackground(new Color(255, 153, 255));
    }//GEN-LAST:event_bilReportMouseEntered

    private void bilReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bilReportMouseExited
        // TODO add your handling code here:
        bilReport.setBackground(new Color(23, 127, 117));
    }//GEN-LAST:event_bilReportMouseExited

    private void bilReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilReportActionPerformed
        String sqlReport = "call state_por()";
        co.report("src\\watersupply\\statementReport.jrxml", sqlReport);  
    
    }//GEN-LAST:event_bilReportActionPerformed

    private void sBilReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sBilReportMouseEntered
      sBilReport.setBackground(new Color(255, 153, 255));
    }//GEN-LAST:event_sBilReportMouseEntered

    private void sBilReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sBilReportMouseExited
        sBilReport.setBackground(new Color(23, 127, 117));
    }//GEN-LAST:event_sBilReportMouseExited

    private void sBilReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sBilReportActionPerformed
        // TODO add your handling code here:
        String sqlReport = "call singleBills_pro('"+singleBilsReport+"')";
        co.report("src\\watersupply\\singleBillsReports.jrxml", sqlReport);  
    
    }//GEN-LAST:event_sBilReportActionPerformed

    private void singReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singReportsActionPerformed
        // TODO add your handling code here:
        String array[] = singReports.getSelectedItem().toString().split(",");
        singleReports = array[0];
        
    }//GEN-LAST:event_singReportsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sm = new SimpleDateFormat("yyyy-MM-dd");
        date = sm.format(Sdate.getDate());
        date1 = sm.format(Edate.getDate());
        String btwenTwoDate = "SELECT p.people_no,p.name,p.tell,d.district, d.village, d.zone, SUM(r.amount) AS Total_Paid,rec_date FROM people p, accounts a, receipt r,address d where d.add_no=p.add_no and a.acc_no=r.acc_no and p.people_no=r.people_no and (rec_date BETWEEN '" + date +"'  AND  '"+ date1+"') GROUP BY p.people_no ORDER by p.people_no asc";
        co.report("src\\watersupply\\RecDateReport.jrxml", btwenTwoDate);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBackground(new Color(255, 153, 255));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBackground(new Color(23, 127, 117));
    }//GEN-LAST:event_jButton1MouseExited

    private void usersBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_usersBtnMouseClicked

    private void usersBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersBtnMouseEntered
        // TODO add your handling code here:
        usersBtn.setBackground(new Color(255, 153, 255));
    }//GEN-LAST:event_usersBtnMouseEntered

    private void usersBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersBtnMouseExited
        // TODO add your handling code here:
        usersBtn.setBackground(new Color(23, 127, 117));
    }//GEN-LAST:event_usersBtnMouseExited

    private void usersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersBtnActionPerformed
        // TODO add your handling code here:
        users user = new users();
        user.show();
    }//GEN-LAST:event_usersBtnActionPerformed

    private void jLabel40MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseEntered
        // TODO add your handling code here:
        jLabel40.setForeground(new Color(255, 153, 255));
    }//GEN-LAST:event_jLabel40MouseEntered

    private void jLabel40MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseExited
        // TODO add your handling code here:
        jLabel40.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_jLabel40MouseExited

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
        // TODO add your handling code here:
        aboutMe me = new aboutMe();
        me.show();
        
    }//GEN-LAST:event_jLabel40MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Edate;
    private com.toedter.calendar.JDateChooser Sdate;
    private javax.swing.JLabel TotCus;
    private javax.swing.JLabel TotVil;
    private javax.swing.JButton add;
    private javax.swing.JButton bil;
    private javax.swing.JButton bilReport;
    private javax.swing.JButton cus;
    private javax.swing.JButton expCh;
    private javax.swing.JButton expPay;
    public javax.swing.JButton fan;
    private javax.swing.JButton hom;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel korsaar;
    private javax.swing.JButton logout;
    private javax.swing.JTabbedPane main;
    private javax.swing.JPanel panal1;
    private javax.swing.JPanel panal2;
    private javax.swing.JPanel panal3;
    private javax.swing.JPanel panal4;
    private javax.swing.JPanel panal5;
    private javax.swing.JButton peo;
    private javax.swing.JPanel poeple;
    private javax.swing.JPanel poeple1;
    private javax.swing.JPanel poeple2;
    private javax.swing.JButton rep;
    public javax.swing.JButton rep2;
    private javax.swing.JButton rereport;
    private javax.swing.JButton rereport1;
    private javax.swing.JButton sBilReport;
    private javax.swing.JSeparator sepre;
    private javax.swing.JButton serv;
    private javax.swing.JPanel sidePanal;
    private javax.swing.JComboBox<String> singReports;
    private javax.swing.JComboBox<String> singleBills;
    private javax.swing.JPanel topPanal;
    private javax.swing.JLabel touse;
    private javax.swing.JButton unReceipReport;
    public javax.swing.JLabel userName;
    public javax.swing.JLabel userType;
    public javax.swing.JButton usersBtn;
    // End of variables declaration//GEN-END:variables
}
