/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package watersupply;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Abdullahi Dere
 */
public class exp_payment extends javax.swing.JFrame {
    Codes co = new Codes();
    String id = null;
    String charg;
    String accNumber;
 
    public void display(){
    co.viewTable(Table, "select * from expense_peyment order by exp_py_no asc");
    }
    public void clear(){
    charCom.setSelectedItem("");amount.setText("");accCom.setSelectedItem("");
    }
    
    public exp_payment() {
        initComponents();
         this.setLocationRelativeTo(null);
        this.setTitle("Expenses Payments");
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        String sql = "SELECT ch_no from expense_charge ORDER by ch_no asc";
        String slq1 = "SELECT concat(acc_no,',',acc_name)as accoun from accounts ORDER by acc_no asc";
        String col = "ch_no";
        String col1 = "accoun";
        co.updateComo(charCom, sql, col);
        co.updateComo(accCom, slq1, col1);
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Back1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ser = new javax.swing.JButton();
        serTex = new javax.swing.JTextField();
        ch = new javax.swing.JLabel();
        charCom = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        update1 = new javax.swing.JButton();
        delet = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        ch1 = new javax.swing.JLabel();
        accCom = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(23, 127, 117));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back1.setBackground(new java.awt.Color(23, 127, 117));
        Back1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Back1.setForeground(new java.awt.Color(255, 255, 255));
        Back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back (1).png"))); // NOI18N
        Back1.setText("Back");
        Back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Back1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Back1MouseExited(evt);
            }
        });
        Back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back1ActionPerformed(evt);
            }
        });
        jPanel1.add(Back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 70));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Expenses Charge");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 290, 60));

        ser.setBackground(new java.awt.Color(204, 204, 204));
        ser.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ser.setForeground(new java.awt.Color(0, 51, 51));
        ser.setText("Search");
        ser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serActionPerformed(evt);
            }
        });
        jPanel1.add(ser, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 139, 53));

        serTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serTexActionPerformed(evt);
            }
        });
        jPanel1.add(serTex, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 165, 50));

        ch.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        ch.setForeground(new java.awt.Color(255, 255, 255));
        ch.setText("Charge_no");
        jPanel1.add(ch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        charCom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One" }));
        charCom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                charComItemStateChanged(evt);
            }
        });
        charCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charComActionPerformed(evt);
            }
        });
        jPanel1.add(charCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 227, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ammount");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, -1));

        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        jPanel1.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 200, 38));

        save.setBackground(new java.awt.Color(204, 204, 204));
        save.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        save.setForeground(new java.awt.Color(0, 51, 51));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 139, 51));

        update1.setBackground(new java.awt.Color(204, 204, 204));
        update1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        update1.setForeground(new java.awt.Color(0, 51, 51));
        update1.setText("Update");
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });
        jPanel1.add(update1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 139, 51));

        delet.setBackground(new java.awt.Color(204, 204, 204));
        delet.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        delet.setForeground(new java.awt.Color(0, 51, 51));
        delet.setText("Delete");
        delet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletActionPerformed(evt);
            }
        });
        jPanel1.add(delet, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 139, 51));

        clear.setBackground(new java.awt.Color(204, 204, 204));
        clear.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        clear.setForeground(new java.awt.Color(0, 51, 51));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 139, 51));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 481, 1040, 300));

        ch1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        ch1.setForeground(new java.awt.Color(255, 255, 255));
        ch1.setText("Account_no");
        jPanel1.add(ch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        accCom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One" }));
        accCom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                accComItemStateChanged(evt);
            }
        });
        accCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accComActionPerformed(evt);
            }
        });
        jPanel1.add(accCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 227, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back1MouseEntered
        // TODO add your handling code here:
        Back1.setBackground(new Color(255,153,255));
    }//GEN-LAST:event_Back1MouseEntered

    private void Back1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back1MouseExited
        // TODO add your handling code here:
        Back1.setBackground(new Color( 23, 127, 117));
    }//GEN-LAST:event_Back1MouseExited

    private void Back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back1ActionPerformed
        DashBoard dash= new DashBoard();
        dash.show();
        this.hide();
    }//GEN-LAST:event_Back1ActionPerformed

    private void serActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serActionPerformed
        String sql = "SELECT exp_py_no, exch.ch_no,xp.amount, concat(a.acc_no,',',a.acc_name) as accNomb FROM expense_charge exch,accounts a,expense_peyment xp WHERE exch.ch_no = xp.ch_no and a.acc_no = xp.acc_no and exp_py_no ='"+serTex.getText()+"'";
        co.search(sql);
        //SimpleDateFormat sm = new SimpleDateFormat("yyyy-mm-dd");
        //date = sm.format(reg_date.getDate());
        try{

            if(co.rs.next()){
                id = co.rs.getString("exp_py_no");
                String selected = co.rs.getString("ch_no");
                charCom.setSelectedItem(selected);
                amount.setText(co.rs.getString("amount"));
               String selected1 = co.rs.getString("accNomb");
                accCom.setSelectedItem(selected1);
                serTex.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "record not found");
            }
        }catch(Exception exp){
            JOptionPane.showMessageDialog(null,exp.getMessage());
        }
    }//GEN-LAST:event_serActionPerformed

    private void serTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serTexActionPerformed

    private void charComItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_charComItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_charComItemStateChanged

    private void charComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charComActionPerformed
        // TODO add your handling code here:
        String array[] = charCom.getSelectedItem().toString().split(",");
        charg = array[0];
    }//GEN-LAST:event_charComActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        //        SimpleDateFormat sm = new SimpleDateFormat("yyyy-MM-dd");
        //        date = sm.format(reg_date.getDate());
        if(charCom.getSelectedItem() != null || amount.getText() != "" || accCom.getSelectedItem() != "" ){

            String oper = "insert";
            String sql = "call expPyment_pro('"+ charg+"','"+amount.getText()+"','"+accNumber+"','"+oper+"',null)";
            co.setSQL(sql);
            clear();
            display();
        }
        else{
            JOptionPane.showConfirmDialog(null, "Please Fill all the blanks");
        }
    }//GEN-LAST:event_saveActionPerformed

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed

        String oper = "update";
        String sql = "call expPyment_pro('"+ charg+"','"+amount.getText()+"','"+accNumber+"','"+oper+"','"+id+"')";
        co.setSQL(sql);
        clear();
        display();
    }//GEN-LAST:event_update1ActionPerformed

    private void deletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletActionPerformed

        String oper = "delete";
        String sql = "call expPyment_pro('"+ charg+"','"+amount.getText()+"','"+accNumber+"','"+oper+"','"+id+"')";
        co.setSQL(sql);
        clear();
        display();
    }//GEN-LAST:event_deletActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // update
    }//GEN-LAST:event_clearActionPerformed

    private void accComItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_accComItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_accComItemStateChanged

    private void accComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accComActionPerformed
        // TODO add your handling code here:
        String array[] = accCom.getSelectedItem().toString().split(",");
        accNumber = array[0];
    }//GEN-LAST:event_accComActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exp_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exp_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exp_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exp_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new exp_payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back1;
    private javax.swing.JTable Table;
    private javax.swing.JComboBox<String> accCom;
    private javax.swing.JTextField amount;
    private javax.swing.JLabel ch;
    private javax.swing.JLabel ch1;
    private javax.swing.JComboBox<String> charCom;
    private javax.swing.JButton clear;
    private javax.swing.JButton delet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton save;
    private javax.swing.JButton ser;
    private javax.swing.JTextField serTex;
    private javax.swing.JButton update1;
    // End of variables declaration//GEN-END:variables
}
