/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package watersupply;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Abdullahi Dere
 */
public class homes extends javax.swing.JFrame {
    Codes co = new Codes();
    String awners = "";
    String addresss = "";
    public void display(){
    co.viewTable(Table, "select * from homes");
    }
    String id = null;
    public void clear(){
        String Select = "Select One";
    own.setSelectedItem(Select); addNo.setSelectedItem(Select);
    }

    /**
     * Creates new form homes
     */
    public homes() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Home Registration");
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        display();
        String sql = "SELECT concat(add_no, ',',village,',',zone) As Adress  FROM address ORDER BY add_no ASC";
        String sql1 = "SELECT concat(people_no,', ',name)as person FROM people ORDER by people_no ASC";
        String col = "Adress";
        String col1 = "person";
        co.updateComo(addNo,sql,col);
        co.updateComo(own,sql1,col1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addNo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        own = new javax.swing.JComboBox<>();
        update = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        del = new javax.swing.JButton();
        sear = new javax.swing.JButton();
        field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(23, 127, 117));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Register New Home");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 320, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Owner");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Add_No");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 97, -1, -1));

        addNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One" }));
        addNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNoActionPerformed(evt);
            }
        });
        jPanel1.add(addNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 112, 227, 40));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 1000, 440));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Homes Preview");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 306, 328, 55));

        save.setBackground(new java.awt.Color(204, 204, 204));
        save.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        save.setForeground(new java.awt.Color(0, 51, 51));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 237, 139, 51));

        own.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One" }));
        own.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownActionPerformed(evt);
            }
        });
        jPanel1.add(own, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 116, 227, 40));

        update.setBackground(new java.awt.Color(204, 204, 204));
        update.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        update.setForeground(new java.awt.Color(0, 51, 51));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 237, 139, 51));

        clear.setBackground(new java.awt.Color(204, 204, 204));
        clear.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        clear.setForeground(new java.awt.Color(0, 51, 51));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 237, 139, 51));

        del.setBackground(new java.awt.Color(204, 204, 204));
        del.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        del.setForeground(new java.awt.Color(0, 51, 51));
        del.setText("Delete");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        jPanel1.add(del, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 139, 51));

        sear.setBackground(new java.awt.Color(204, 204, 204));
        sear.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        sear.setForeground(new java.awt.Color(0, 51, 51));
        sear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        sear.setText("Search");
        sear.setIconTextGap(2);
        sear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searActionPerformed(evt);
            }
        });
        jPanel1.add(sear, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 190, 60));

        field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldActionPerformed(evt);
            }
        });
        jPanel1.add(field, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNoActionPerformed
     String array[] = addNo.getSelectedItem().toString().split(",");
     addresss = array[0];
    }//GEN-LAST:event_addNoActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed

        if(own.getSelectedItem().equals("Select One") || addNo.getSelectedItem().equals("Select One") ){
            JOptionPane.showMessageDialog(null, "Please Fill All The Blanks");
        }
        else{
           String oper = "insert";
           String sql = "call hom_pro('"+ awners+"','"+addresss+"','"+oper+"',null)";
           co.setSQL(sql);
           clear();
           display();
        }
    }//GEN-LAST:event_saveActionPerformed

    private void ownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownActionPerformed
        // TODO add your handling code here:
        String array[] = own.getSelectedItem().toString().split(",");
        awners = array[0];
    }//GEN-LAST:event_ownActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        if(id== null){
            JOptionPane.showMessageDialog(null, "Please Search Valid Id, Then delete");
        }else{
        String oper = "update";
        String sql = "call hom_pro('"+awners+"','"+addresss+"','"+oper+"','"+id+"')";
          co.setSQL(sql);
          clear();
        }
    }//GEN-LAST:event_updateActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
      clear(); 
    }//GEN-LAST:event_clearActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        if(id== null){
            JOptionPane.showMessageDialog(null, "Please Search Valid Id, Then delete");
        }else{
        String oper = "delete";
        String sql = "call hom_pro('"+awners+"','"+addresss+"','"+oper+"','"+id+"')";
        co.setSQL(sql);
        }
    }//GEN-LAST:event_delActionPerformed

    private void searActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searActionPerformed
        // TODO add your handling code here:
        String sql = "select h_no, concat(people_no,', ',name) as mulkile, concat(a.add_no,',',a.village,',',a.zone) as addNumb from address a, people p,homes h where a.add_no = p.add_no and p.people_no = h.owner and h.add_no = a.add_no and h_no ='"+field.getText()+"'";
      co.search(sql);
      try{
      if(co.rs.next()){
      id = co.rs.getString("h_no");
      String selected = co.rs.getString("mulkile");
      String selected1 = co.rs.getString("addNumb");
      own.setSelectedItem(selected);
      addNo.setSelectedItem(selected1);
      field.setText("");
      }else{
      JOptionPane.showMessageDialog(null, "record not found");
      }
      }catch(Exception exp){
      JOptionPane.showMessageDialog(null,exp.getMessage());
      }
    }//GEN-LAST:event_searActionPerformed

    private void fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JComboBox<String> addNo;
    private javax.swing.JButton clear;
    private javax.swing.JButton del;
    private javax.swing.JTextField field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> own;
    private javax.swing.JButton save;
    private javax.swing.JButton sear;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
