/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package watersupply;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static org.codehaus.groovy.tools.shell.util.Preferences.clear;

/**
 *
 * @author Abdullahi Dere
 */
public class register2 extends javax.swing.JFrame {
Codes co = new Codes();
String type;
public void clear(){
    email.setText("");
    usname.setText(""); pass.setText("");conpass.setText("");
    }
    /**
     * Creates new form users
     */
    public register2() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Water Managemet System");
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        conpass = new javax.swing.JPasswordField();
        signupBott = new javax.swing.JButton();
        Back_bottum = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        email = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        userr = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        secNo = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoWater-01.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 570));

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 70)); // NOI18N
        jLabel1.setText("Sign up");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (1).png"))); // NOI18N
        jLabel2.setText("User name");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 42));

        usname.setBackground(new java.awt.Color(255, 204, 255));
        usname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usname.setBorder(null);
        jPanel3.add(usname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 264, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (1).png"))); // NOI18N
        jLabel3.setText("User_type");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 120, 44));

        pass.setBackground(new java.awt.Color(255, 204, 255));
        pass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pass.setBorder(null);
        jPanel3.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 261, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lock-up.png"))); // NOI18N
        jLabel4.setText("Confirm");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 109, 52));

        conpass.setBackground(new java.awt.Color(255, 204, 255));
        conpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        conpass.setBorder(null);
        conpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conpassActionPerformed(evt);
            }
        });
        jPanel3.add(conpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 372, 264, 30));

        signupBott.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        signupBott.setForeground(new java.awt.Color(51, 51, 255));
        signupBott.setText("Sign up");
        signupBott.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBottActionPerformed(evt);
            }
        });
        jPanel3.add(signupBott, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 134, 51));

        Back_bottum.setBackground(new java.awt.Color(255, 255, 255));
        Back_bottum.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Back_bottum.setText("Sign In");
        Back_bottum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_bottumActionPerformed(evt);
            }
        });
        jPanel3.add(Back_bottum, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 166, 53));

        jSeparator1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 264, 13));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 261, 13));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 255));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 403, 263, 10));

        email.setBackground(new java.awt.Color(255, 204, 255));
        email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        email.setBorder(null);
        jPanel3.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 264, 30));

        jSeparator4.setBackground(new java.awt.Color(51, 51, 255));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 264, 13));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new1.png"))); // NOI18N
        jLabel6.setText("Email");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 100, 42));

        userr.setBackground(new java.awt.Color(255, 204, 255));
        userr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userr.setText("User");
        userr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userrActionPerformed(evt);
            }
        });
        jPanel3.add(userr, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 90, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lock-up.png"))); // NOI18N
        jLabel7.setText("Password");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 44));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lock-up.png"))); // NOI18N
        jLabel8.setText("Sec_no");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 109, 52));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 255));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 263, 10));

        secNo.setBackground(new java.awt.Color(255, 204, 255));
        secNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        secNo.setBorder(null);
        secNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secNoActionPerformed(evt);
            }
        });
        jPanel3.add(secNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 264, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 1, 500, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void conpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conpassActionPerformed

    private void signupBottActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBottActionPerformed

        if(usname.getText().equals("") ||  email.getText().equals("")||  type.equals("")){
            JOptionPane.showMessageDialog(null, "Please Fill the blanks");
        }else{
            if(pass.getText().equals(conpass.getText())){
                String oper = "insert";
                String sql = "call users_pro('" + usname.getText() + "','" + email.getText() + "','" + type + "','" + pass.getText() + "','"+ secNo.getText() +"','" + oper + "',null)";
                co.setSQL(sql);
                clear();
            }
            else{
                JOptionPane.showConfirmDialog(null, "Not Matched!");
            }

        }

    }//GEN-LAST:event_signupBottActionPerformed

    private void Back_bottumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_bottumActionPerformed
        // TODO add your handling code here:
        login log = new login();
        log.show();
        this.hide();
    }//GEN-LAST:event_Back_bottumActionPerformed

    private void userrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userrActionPerformed
        // TODO add your handling code here:
        type = userr.getText();
    }//GEN-LAST:event_userrActionPerformed

    private void secNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_bottum;
    private javax.swing.JPasswordField conpass;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField secNo;
    private javax.swing.JButton signupBott;
    private javax.swing.JRadioButton userr;
    private javax.swing.JTextField usname;
    // End of variables declaration//GEN-END:variables
}
